project:
  type: website
  output-dir: docs

website:
  repo-url: https://github.com/ongayumi/codecub_website
  repo-actions: [edit,issue]
  title: "Brazilian Dishes"
  favicon: "Flag_of_Brazil.png"
  navbar:
    right: 
      - href: "https://github.com/ongayumi/codecub_website"
        icon: github
    left:
      - href: index.qmd
        text: Home
        icon: globe-americas
      - href: about.qmd
        text: About
      - href: salty-food.qmd
        text: "Salty food"
        icon: chevron-bar-right
      - href: sweet-food.qmd
        text: "Sweet food"
        icon: chevron-bar-right
      - text: Occasions
        menu:
        - text: Birthday Parties
          href: pages/setup.qmd
        - text: Christmas
          href: pages/r_resources.qmd
        - text: New Year
          href: pages/setup.qmd
        - text: Picnic
          href: pages/setup.qmd
        - text: Snacks
          href: pages/setup.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true
    mainfont: Proxima Nova



